### ISSUE TITLE
no presence of its-tool-ref property

### ISSUE THREAD

**Issue by m1ci** [freme-project/e-Internationalization#32]
In the results provided in the https://github.com/freme-project/e-Internationalization/issues/30#issuecomment-175468814 there is no presence of the its-tool-ref property. Not sure if this has been considered/implemented already, but I think its good to highlight that.

**Comment by borriellom** [comment]
It is neither implemented nor considered at the moment. As now I'm changing the code for fixing the multiple attributes issue  (see comments in #30), I'm going to check if I can easily add this property as well.

**Comment by m1ci** [comment]
OK, thanks for clarification. Lets leave this issue open for the time being.

**Comment by borriellom** [comment]
The issue #30 is fixed now. I couldn't insert this property because I don't know how to use it. I thought it was a simple conversion from a NIF property to a HTML attribute. So I agree, let's leave this issue opened for now.

**Comment by m1ci** [comment]
whats the status of this issue?
I still dont see this information in HTML.

In RDF its itsrdf:taAnnotatorsRef, in HTMl should be its-annotators-ref. Can we have this done @borriellom or @katia-vistatec ?

\cc @jnehring

**Comment by katia-vistatec** [comment]
Ok.

**Comment by katia-vistatec** [comment]
[input-out-local.txt](https://github.com/freme-project/e-Internationalization/files/558679/input-out-local.txt)
[input-out-dev.txt](https://github.com/freme-project/e-Internationalization/files/558680/input-out-dev.txt)

**Comment by katia-vistatec** [comment]
curl -X POST --header "Content-Type: text/html" --data "@input.txt" --header "Accept: text/html" "http://api-dev.freme-project.eu/current/e-terminology/tilde?informat=text/html&outformat=text/html&source-lang=en&target-lang=nl&nif-version=2.1" > input-out-dev.txt
curl -X POST --header "Content-Type: text/html" --data "@input.txt" --header "Accept: text/html" "http://localhost:8080/e-terminology/tilde?informat=text/html&outformat=text/html&source-lang=en&target-lang=nl&nif-version=2.1" > input-out-local.txt

**Comment by katia-vistatec** [comment]
If I run it locally (second curl request) I obtain input-ou-local.txt as the output and it has the its-ta-annotators-ref attribute inside the HTML tag.
If I run it pointing to api-dev (first curl request)  I don't see the attribute (see output file attached input-out-dev.txt).
So I think It's a version problem. Maybe the artifact version of internationalization that is being used is not the one containing the implementation.

**Comment by m1ci** [comment]
ok, thanks for the info.
@jnehring can you investigate the problem?
@katia-vistatec can you please generate one output example using FREME NER? Thanks!

**Comment by katia-vistatec** [comment]
Freme ner I can't debug it locally. If I do:

curl -X POST --header "Content-Type: text/html" --header "Accept: text/html" --data "@input.txt" "http://api-dev.freme-project.eu/current/e-entity/freme-ner/documents?informat=text%2Fhtml&outformat=text%2Fhtml&language=en&dataset=dbpedia&mode=all" > input-out-ner-dev.txt

the output does not contain the annotators-ref attribute.

**Comment by m1ci** [comment]
why there is no annotators-ref attribute for freme ner? any ideas?

**Comment by katia-vistatec** [comment]
Because of the same version problem. Indeed in the curl there is http://api-dev.freme-project.eu/current.

**Comment by m1ci** [comment]
>  Indeed in the curl there is http://api-dev.freme-project.eu/current.

Are you saying that it should work for API dev?

I try to send:

[data.txt](https://github.com/freme-project/e-Internationalization/files/558782/data.txt)

and run

```
curl -X POST --header "Content-Type: text/html" --header "Accept: text/html" -d @data.txt "http://api-dev.freme-project.eu/current/e-entity/freme-ner/documents?informat=text%2Fhtml&outformat=text%2Fhtml&language=en&dataset=dbpedia&mode=all"
```

but I get no annotators-ref in the output html.

**Comment by katia-vistatec** [comment]
No I am saying that it is currently working only "locally" when I use localhost:8080 in the curl request but not on API dev so every curl request to api dev is not working. 
There was a previous issue that Jan closed and at that time it was working also on dev.
I think it is a version problem. The artifactId of internationalization is not the one that contains the implementation.

**Comment by katia-vistatec** [comment]
See https://github.com/freme-project/basic-services/issues/111

**Comment by katia-vistatec** [comment]
Could be that broker-dev is pointing to internationalization jar 0.6 and this version does not contain the implementation of annotators-ref attribute. This can easily happen because of default artifact versions and "dependencyManagement" in freme-parent pom.

**Comment by jnehring** [comment]
I updated e-Internationalization on freme-dev to the latest version 0.8-SNAPSHOT (see #41). Please test

**Comment by m1ci** [comment]
tested but the `its-tool-ref` property is not found in the output.
I send [data.txt](https://github.com/freme-project/e-Internationalization/files/558782/data.txt) by executing

```
curl -X POST --header "Content-Type: text/html" --header "Accept: text/html" -d @data.txt "http://api-dev.freme-project.eu/current/e-entity/freme-ner/documents?informat=text%2Fhtml&outformat=text%2Fhtml&language=en&dataset=dbpedia&mode=all"
```

and the results are

```
<html>
 <head> 
  <title>dummy title</title> 
 </head> 
 <body> 
  <p><span data-its-ta-class-refs="http://www.w3.org/2002/07/owl#Thing http://dbpedia.org/ontology/Film http://dbpedia.org/ontology/Wikidata:Q11424 http://dbpedia.org/ontology/Work" its-ta-class-ref="http://www.w3.org/2002/07/owl#Thing" its-ta-confidence="0.5022401140252479" its-ta-ident-ref="http://dbpedia.org/resource/Welcome_(2007_film)">Welcome</span> to the city of <span data-its-ta-class-refs="http://dbpedia.org/ontology/Region http://dbpedia.org/ontology/Location http://nerd.eurecom.fr/ontology#Location http://dbpedia.org/ontology/AdministrativeRegion http://dbpedia.org/ontology/Place http://dbpedia.org/ontology/PopulatedPlace" its-ta-class-ref="http://dbpedia.org/ontology/Region" its-ta-confidence="0.6846576547715328" its-ta-ident-ref="http://dbpedia.org/resource/Berlin">Berlin</span>!</p>  
 </body>
</html>
```

I think I found why is that. I use nif-version 2.0 and there is no `itsrdf:taAnnotatorsRef` information.
@sandroacoelho please add itsrdf:taAnnotatorsRef also for NIF 2.0?

I have two questions for @borriellom @katia-vistatec:

1) does e-Internationalization understand NIF 2.1?

2) why do you add the `its-tool-ref` property in the <html > element? the `its-tool-ref` should be at the annotation level, in the same element where you attach the entity link, types, etc.  I think this should be fixed. This happens for e-terminology but also for e-entity if I call with nif 2.1

**Comment by katia-vistatec** [comment]
Yes, internationalization handles nif 2.1. The itsrdf:taAnnotatorsRef  has been added only for nif 2.1. It has been added in the HTML tag in case of an HTML file or in the outermost element in case of an HTML snippet.

**Comment by m1ci** [comment]
ok, so why its-tool-ref is not present in the FREME NER output (in: HTML, out: HTML)?

**Comment by katia-vistatec** [comment]
The curl here has no nif-version parameter.

**Comment by m1ci** [comment]
but even if I put nif-version=2.1 it does not work 
try:

```
curl -X POST --header "Content-Type: text/html" --header "Accept: text/html" -d @data.txt "http://api-dev.freme-project.eu/current/e-entity/freme-ner/documents?informat=text%2Fhtml&outformat=text%2Fhtml&language=en&dataset=dbpedia&mode=all&nif-version=2.1"
```

**Comment by katia-vistatec** [comment]
I was trying to ask for a nif output to see if the property is in the nif file but I can't connect to the host. Can you try it?

**Comment by m1ci** [comment]
what host? freme ner dev is up and running.

**Comment by m1ci** [comment]
also, if I process

```
<html>
 <head> 
  <title></title> 
 </head> 
 <body> 
  <p>Welcome to Europe.</p> 
 </body>
</html>
```

I get 

```
<html its-ta-annotators-ref="http://freme-project.eu/tools/freme-ner">
 <head> 
  <title></title> 
 </head> 
 <body> 
  <p>Welcome to Europe.</p> 
 </body>
</html>
```

but the entities are  not annotated (in <span> element).

**Comment by m1ci** [comment]
during a dev telco decided to close the issue
